### ISSUE TITLE
Allow Magento 2 widget in wordpress content to be passed to Magento front-end

### ISSUE THREAD

**Issue by GrimLink** [mooore-digital/magento2-module-wordpress-integration-cms#35]
Currently when using a Magento 2 widget in Wordpress as embed will not output it.
As it is escaped as none valid html string.

Adding Magento 2 widgets to the Wordpress content would make it easier use product related widgets between the content.
Or more.

**Comment by poespas** [comment]
@GrimLink This is now possible through the changes in PR #36 , which is about to release. I will close this issue now.
